language: python
python:
    - "3.5"
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script: python3 setup.py test
after_success:
    - coveralls
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi
addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
    coverity_scan:
        project:
            name: "soudegesu/rounding_nurse"
            description: "Build submitted via Travis CI"
        build_command_prepend: ""
        build_command: ""
        branch_pattern: master