mysql:
  build: .
  dockerfile: Dockerfile
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=crawl
    - MYSQL_USER=soudegesu
    - MYSQL_PASSWORD=soudegesu
  volumes:
    - ./init.d:/docker-entrypoint-initdb.d
